# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DP832_ion1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(820, 464)
        self.Oven_CH1_ON = QtWidgets.QPushButton(Form)
        self.Oven_CH1_ON.setGeometry(QtCore.QRect(70, 180, 111, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.Oven_CH1_ON.setFont(font)
        self.Oven_CH1_ON.setObjectName("Oven_CH1_ON")
        self.Oven_CH1_OFF = QtWidgets.QPushButton(Form)
        self.Oven_CH1_OFF.setGeometry(QtCore.QRect(70, 300, 111, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.Oven_CH1_OFF.setFont(font)
        self.Oven_CH1_OFF.setObjectName("Oven_CH1_OFF")
        self.Flip_CH2_ON = QtWidgets.QPushButton(Form)
        self.Flip_CH2_ON.setGeometry(QtCore.QRect(630, 180, 111, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.Flip_CH2_ON.setFont(font)
        self.Flip_CH2_ON.setObjectName("Flip_CH2_ON")
        self.Flip_CH2_OFF = QtWidgets.QPushButton(Form)
        self.Flip_CH2_OFF.setGeometry(QtCore.QRect(630, 300, 111, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.Flip_CH2_OFF.setFont(font)
        self.Flip_CH2_OFF.setObjectName("Flip_CH2_OFF")
        self.PMT_CH3_ON = QtWidgets.QPushButton(Form)
        self.PMT_CH3_ON.setGeometry(QtCore.QRect(410, 180, 111, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.PMT_CH3_ON.setFont(font)
        self.PMT_CH3_ON.setObjectName("PMT_CH3_ON")
        self.PMT_CH3_OFF = QtWidgets.QPushButton(Form)
        self.PMT_CH3_OFF.setGeometry(QtCore.QRect(410, 300, 111, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.PMT_CH3_OFF.setFont(font)
        self.PMT_CH3_OFF.setObjectName("PMT_CH3_OFF")
        self.Oven_CH1 = QtWidgets.QLabel(Form)
        self.Oven_CH1.setGeometry(QtCore.QRect(70, 60, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Oven_CH1.setFont(font)
        self.Oven_CH1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Oven_CH1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Oven_CH1.setAlignment(QtCore.Qt.AlignCenter)
        self.Oven_CH1.setObjectName("Oven_CH1")
        self.Flip_CH2 = QtWidgets.QLabel(Form)
        self.Flip_CH2.setGeometry(QtCore.QRect(630, 60, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Flip_CH2.setFont(font)
        self.Flip_CH2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Flip_CH2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Flip_CH2.setAlignment(QtCore.Qt.AlignCenter)
        self.Flip_CH2.setObjectName("Flip_CH2")
        self.PMT_CH3 = QtWidgets.QLabel(Form)
        self.PMT_CH3.setGeometry(QtCore.QRect(410, 60, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PMT_CH3.setFont(font)
        self.PMT_CH3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.PMT_CH3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PMT_CH3.setAlignment(QtCore.Qt.AlignCenter)
        self.PMT_CH3.setObjectName("PMT_CH3")
        self.Oven_CH1_state = QtWidgets.QTextBrowser(Form)
        self.Oven_CH1_state.setGeometry(QtCore.QRect(70, 110, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.Oven_CH1_state.setFont(font)
        self.Oven_CH1_state.setObjectName("Oven_CH1_state")
        self.Flip_CH2_state = QtWidgets.QTextBrowser(Form)
        self.Flip_CH2_state.setGeometry(QtCore.QRect(630, 110, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.Flip_CH2_state.setFont(font)
        self.Flip_CH2_state.setObjectName("Flip_CH2_state")
        self.PMT_CH3_state = QtWidgets.QTextBrowser(Form)
        self.PMT_CH3_state.setGeometry(QtCore.QRect(410, 110, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.PMT_CH3_state.setFont(font)
        self.PMT_CH3_state.setObjectName("PMT_CH3_state")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(600, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Oven_CH2_ON = QtWidgets.QPushButton(Form)
        self.Oven_CH2_ON.setGeometry(QtCore.QRect(240, 180, 111, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.Oven_CH2_ON.setFont(font)
        self.Oven_CH2_ON.setObjectName("Oven_CH2_ON")
        self.Oven_CH2 = QtWidgets.QLabel(Form)
        self.Oven_CH2.setGeometry(QtCore.QRect(240, 60, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Oven_CH2.setFont(font)
        self.Oven_CH2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Oven_CH2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Oven_CH2.setAlignment(QtCore.Qt.AlignCenter)
        self.Oven_CH2.setObjectName("Oven_CH2")
        self.Oven_CH2_OFF = QtWidgets.QPushButton(Form)
        self.Oven_CH2_OFF.setGeometry(QtCore.QRect(240, 300, 111, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.Oven_CH2_OFF.setFont(font)
        self.Oven_CH2_OFF.setObjectName("Oven_CH2_OFF")
        self.Oven_CH2_state = QtWidgets.QTextBrowser(Form)
        self.Oven_CH2_state.setGeometry(QtCore.QRect(240, 110, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.Oven_CH2_state.setFont(font)
        self.Oven_CH2_state.setObjectName("Oven_CH2_state")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(370, 10, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Oven_CH1_ON.setText(_translate("Form", "O N"))
        self.Oven_CH1_OFF.setText(_translate("Form", "OFF"))
        self.Flip_CH2_ON.setText(_translate("Form", "O N"))
        self.Flip_CH2_OFF.setText(_translate("Form", "OFF"))
        self.PMT_CH3_ON.setText(_translate("Form", "O N"))
        self.PMT_CH3_OFF.setText(_translate("Form", "OFF"))
        self.Oven_CH1.setText(_translate("Form", "CH 1"))
        self.Flip_CH2.setText(_translate("Form", "CH 2"))
        self.PMT_CH3.setText(_translate("Form", "CH 3"))
        self.Oven_CH1_state.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Flip_CH2_state.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.PMT_CH3_state.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("Form", "DP832A-Flip"))
        self.Oven_CH2_ON.setText(_translate("Form", "O N"))
        self.Oven_CH2.setText(_translate("Form", "CH 2"))
        self.Oven_CH2_OFF.setText(_translate("Form", "OFF"))
        self.Oven_CH2_state.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("Form", "DP832A-Oven"))
        self.label_3.setText(_translate("Form", "DP832A-PMT"))

